# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Public/Global.h \
    ./Public/QtFrame/DX11RenderEngine.h \
    ./Public/QtFrame/RenderViewport.h \
    ./Public/Render/camera.h \
    ./Public/Render/GeometryFactory.h \
    ./Public/Render/Graphics.h \
    ./Public/Render/GraphicsResource.h \
    ./Public/Render/Mesh.h \
    ./Public/Render/ModelResFactory.h \
    ./Public/Render/Texture.h \
    ./Public/Render/VertexLayout.h \
    ./Public/Render/Bindable/BindableInterface.h \
    ./Public/Render/Bindable/ConstantBuffer.h \
    ./Public/Render/Bindable/DepthStencil.h \
    ./Public/Render/Bindable/IndexBuffer.h \
    ./Public/Render/Bindable/InputLayout.h \
    ./Public/Render/Bindable/LightBuffer.h \
    ./Public/Render/Bindable/PixelShader.h \
    ./Public/Render/Bindable/TransformBuffer.h \
    ./Public/Render/Bindable/VertexBuffer.hpp \
    ./Public/Render/Bindable/VertexShader.h \
    ./Public/Render/Drawable/Coordinate.h \
    ./Public/Render/Drawable/Drawable.h \
    ./Public/Render/Shape/Box.h \
    ./Public/Render/Shape/Model.h \
    ./Public/Render/Shape/Plane.h \
    ./Public/Render/Shape/Shape.hpp \
    ./Public/Render/ResManage/MeshFactory.h \
    ./Public/Render/ResManage/ResManage.h \
    ./Public/Render/ResManage/TextureFactory.h \
    ./Public/Render/Light/LightAttribute.h \
    ./Public/Render/Light/DirectionalLight.h \
    ./Public/Render/Light/Light.h \
    ./Public/Render/Light/LightSet.h \
    ./Public/Render/Light/PointLight.h \
    ./Public/Render/Light/SpotLight.h \
    ./Public/Tool/ObserverInterface.h \
    ./Public/Tool/Subject.h \
    ./Public/Tool/Timer.h \
    ./Public/Tool/Utili.h
SOURCES += ./Private/Global.cpp \
    ./Private/main.cpp \
    ./Private/Render/camera.cpp \
    ./Private/Render/GeometryFactory.cpp \
    ./Private/Render/Graphics.cpp \
    ./Private/Render/GraphicsResource.cpp \
    ./Private/Render/Mesh.cpp \
    ./Private/Render/ModelResFactory.cpp \
    ./Private/Render/Texture.cpp \
    ./Private/Render/VertexLayout.cpp \
    ./Private/Render/Bindable/DepthStencil.cpp \
    ./Private/Render/Bindable/IndexBuffer.cpp \
    ./Private/Render/Bindable/InputLayout.cpp \
    ./Private/Render/Bindable/LightBuffer.cpp \
    ./Private/Render/Bindable/PixelShader.cpp \
    ./Private/Render/Bindable/TransformBuffer.cpp \
    ./Private/Render/Bindable/VertexBuffer.cpp \
    ./Private/Render/Bindable/VertexShader.cpp \
    ./Private/Render/Drawable/Coordinate.cpp \
    ./Private/Render/Drawable/Drawable.cpp \
    ./Private/Render/Drawable/Box.cpp \
    ./Private/Render/Shape/Model.cpp \
    ./Private/Render/Shape/Plane.cpp \
    ./Private/Render/ResManage/MeshFactory.cpp \
    ./Private/Render/ResManage/ResManage.cpp \
    ./Private/Render/ResManage/TextureFactory.cpp \
    ./Private/Render/Light/DirectionalLight.cpp \
    ./Private/Render/Light/Light.cpp \
    ./Private/Render/Light/PointLight.cpp \
    ./Private/Render/Light/SpotLight.cpp \
    ./Private/Tool/Timer.cpp \
    ./Public/Tool/Subject.cpp \
    ./Private/QtFrame/DX11RenderEngine.cpp \
    ./Private/QtFrame/RenderViewport.cpp
FORMS += ./DX11RenderEngine.ui \
    ./RenderViewport.ui
RESOURCES += DX11RenderEngine.qrc
